[package]
name = "img-uploader"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = {workspace = true}
serde = {workspace = true}
ic-agent = {workspace = true}
ic-utils = {workspace = true}
tokio = {version = "1.44.2", features = ["full"]}
glob = "0.3.2"
bot_api = {path = "../bot/api"}