[package]
name = "minter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = {workspace = true}
ic-cdk = {workspace = true}
ic-cdk-timers = {workspace = true}
ic-stable-structures = {workspace = true}
icrc-ledger-types = {workspace = true}
icrc7-types = {workspace = true}
serde = {workspace = true}
rmp-serde = {workspace = true}
sha2 = {workspace = true}
hex = {workspace = true}
futures = {workspace = true}
crypto-bigint = {workspace = true}
rand = {workspace = true}
getrandom = {workspace = true}
